sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t 20039867/green .
  - docker run 20039867/green -c "ant"
  - docker ps -a
  - docker run 20039867/green -c "ant test"
