sudo: required

services:
  - docker
  
language: java

script:
 - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
 - export REPO=20039867/green
 - docker build -t $REPO:$TAG -f Dockerfile .
 - docker ant;
 - docker ant test;

