sudo: required

language: java

services:
  - docker

before_install:
  - docker build -t 20039867/green .
  
before_script:
   - sudo apt-get install ant-optional

script:
  - docker exec "ant; ant test"
